import argparse
import sys
import os


def write_submitter(path_sh):
    '''Receives a path to the
    sh files and prints a bash
    script to submit them'''

    files = os.listdir(path_sh)
    command_line = "#!bin/bash\n"
    to_write = command_line
    
    for index, sh in enumerate(files, start=1):
        to_sub = "sbatch " + os.path.join(path_sh,sh)

        if index % 10 != 0:
            to_write += to_sub + "\n"

        else:
            to_write += to_sub + "\n"
            to_write += 'sleep 15\n'

    print(to_write)


def main():

    path_sh = args.path
    write_submitter(path_sh)



if __name__ == "__main__":

    parser = argparse.ArgumentParser(

            description = "A tool to write a main.sh file to submit each .sh generated by writer_submitter_downl.py with an interval of 15 seconds"

    )
 
    parser.add_argument('-p', '--path', action="store",

                        help='Absolute path to the .sh dir',
                        required=True
    )


    args = parser.parse_args()
    main()
